version: "3"

services:
  light:
    build: .
    restart: unless-stopped
    volumes:
      - "./uploads:/opt/uploads"
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=light
      - POSTGRES_PASSWORD=light
      - POSTGRES_DATABASE=light
    volumes:
      - "/var/lib/postgresql-light:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U light"]
      interval: 10s
      timeout: 5s
      retries: 5
